---

- name: Install curl
  ansible.builtin.dnf:
    name: curl
    state: latest

- name: Download k0s
  ansible.builtin.shell: curl -sSLf https://get.k0s.sh | sh

- name: Install k0s
  ansible.builtin.command: /usr/local/bin/k0s install controller --single

- name: Start k0s
  ansible.builtin.command: /usr/local/bin/k0s start

#- name: Status k0s
#  ansible.builtin.shell: /usr/local/bin/k0s status
