---

- name: Add Adoptium repo
  ansible.builtin.yum_repository:
    name: adoptium
    description: Adoptium Temurin JDK
    baseurl: "{{ adoptium_repo_url }}"
    gpgcheck: true
    enabled: true
    gpgkey: "{{ adoptium_repo_gpg }}"

- name: Install Temurin JRE v. {{ temurin_version }}
  ansible.builtin.dnf:
    name: "temurin-{{ temurin_version }}-jre"
    state: present
